version: "3"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres1
      POSTGRES_DB: product
  web:
    # replace username/repo:tag with your name and image details
    image: webpack-docker
    depends_on:
      - db
    links:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 250M
    ports:
      - "3000:3000"
    networks:
      - webnet
networks:
  webnet: